# -*- coding: utf-8 -*-
"""setup.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRFS0lc_3aS5nmyDLIvV6MI_vSOafAgR
"""

from distutils.core import setup

setup(
  name='{game-of-life-ryad_mimouni-CDOF2}',
  version='1.0',
  author='{ryad_mimouni}',
  license='MIT',
  long_description=open('README.md').read(),
)